# main text of home
name: Sebastian Cajas
bio: Research fellow at VCG Harvard | Machine learning intern at EcoVadis | Image Processing and computer vision MsC 

# twitter summary info
description: Academic portfolio

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/me.png

url: https://sebasmos.github.io/

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
#facebook: myfacebook
linkedin: sebasmos777
github: sebasmos777
email: scajasordonez [ad] fas.harvard.edu.co


#authors:
#    Sebastian:
#        name: Sebastian Cajas
 #       bio: An astrophilic homosapiens
 #       external-image: True
 #       picture: assets/images/profile.jpg
        

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true
cv: true
#papers: true
#writing: true
#syllabuses: true
#calendar: true

# if you don't need "about" or "blog", comment them out below
about: True
blog: false

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
